name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [ push ]

env:
  cache_image: ghcr.io/${{ github.repository }}/cache:cache

jobs:
  set-version:
    name: Set variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set version"
        id: constants
        run: |
          export version="$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')"
          echo "::set-output name=version::${version}"
    outputs:
      version: "${{ steps.constants.outputs.version }}"
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: set-version
    env:
      version: "${{ needs.set-version.outputs.version }}"
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and possibly push
        env:
          EARTHLY_PUSH: "${{ github.ref == 'refs/heads/main' }}"
        run: |
          ./earthlyw --version
          ./earthlyw --verbose --allow-privileged --ci --output "--remote-cache=${cache_image}" +build "--version=${version}"
